### ISSUE TITLE
RuntimeWarning: divide by zero encountered in long_scalars 

### ISSUE THREAD

**Issue by mirfan899** [oulenz/fuzzy-rough-learn#6]
Training the FRNN on TFIDF of texts gives an error.

I'm following the FRNN script on iris dataset to classify sentences.

Here is the code I'm using to classify the text.

```python
from frlearn.base import FitPredictClassifier
from frlearn.neighbours import FRFS, FRNN
from frlearn.neighbours import FROVOCO
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

data = pd.read_csv("translated/parts01.txt", names=["intent", "sentence"])
data.dropna(inplace=True)
data.drop_duplicates(inplace=True)
X = data["sentence"].values
y = data["intent"].values

max_feature_num = 100
data_vectorizer = TfidfVectorizer(max_features=max_feature_num)
data_vecs = data_vectorizer.fit_transform(X).toarray()

X_train, X_test, y_train, y_test = train_test_split(data_vecs, y, test_size=0.2)

frnn = FitPredictClassifier(FROVOCO)
frnn.fit(X_train, y_train)
print(frnn.predict(X_test))
```
I'm getting the following error, I tried to fix but it seems there is no solution available.

```shell
/home/irfan/.pyenv/versions/FuzzyClassification/lib/python3.7/site-packages/frlearn/neighbours/classifiers.py:145: RuntimeWarning: divide by zero encountered in long_scalars
  self.ova_ir = np.array([c_n / (len(X) - c_n) for c_n in class_sizes])
Traceback (most recent call last):
  File "/home/irfan/PycharmProjects/FuzzyClasification/test.py", line 27, in <module>
    frnn.fit(X_train, y_train)
  File "/home/irfan/.pyenv/versions/FuzzyClassification/lib/python3.7/site-packages/frlearn/base.py", line 198, in fit
    self.model_ = self.classifier.construct(X, y)
  File "/home/irfan/.pyenv/versions/FuzzyClassification/lib/python3.7/site-packages/frlearn/base.py", line 47, in construct
    return self.Model(self, X, y, *args, **kwargs)
  File "/home/irfan/.pyenv/versions/FuzzyClassification/lib/python3.7/site-packages/frlearn/neighbours/classifiers.py", line 149, in __init__
    co_indices = [classifier.nn_search.construct(co_C) for co_C in co_Cs]
  File "/home/irfan/.pyenv/versions/FuzzyClassification/lib/python3.7/site-packages/frlearn/neighbours/classifiers.py", line 149, in <listcomp>
    co_indices = [classifier.nn_search.construct(co_C) for co_C in co_Cs]
  File "/home/irfan/.pyenv/versions/FuzzyClassification/lib/python3.7/site-packages/frlearn/neighbours/neighbour_search.py", line 33, in construct
    return self.Index(self, X)
  File "/home/irfan/.pyenv/versions/FuzzyClassification/lib/python3.7/site-packages/frlearn/neighbours/neighbour_search.py", line 153, in __init__
    self.tree = NearestNeighbors(**search.construction_params).fit(X)
  File "/home/irfan/.pyenv/versions/FuzzyClassification/lib/python3.7/site-packages/sklearn/neighbors/_unsupervised.py", line 142, in fit
    return self._fit(X)
  File "/home/irfan/.pyenv/versions/FuzzyClassification/lib/python3.7/site-packages/sklearn/neighbors/_base.py", line 397, in _fit
    X = self._validate_data(X, accept_sparse='csr')
  File "/home/irfan/.pyenv/versions/FuzzyClassification/lib/python3.7/site-packages/sklearn/base.py", line 421, in _validate_data
    X = check_array(X, **check_params)
  File "/home/irfan/.pyenv/versions/FuzzyClassification/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/irfan/.pyenv/versions/FuzzyClassification/lib/python3.7/site-packages/sklearn/utils/validation.py", line 672, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 100)) while a minimum of 1 is required.
```

**Comment by oulenz** [comment]
Hi, sorry that I wasn't able to look at this, but I am happy that you managed to find the reason!
